name: full CI

on:
  push:
    branches:
      - musl_ci
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docker_linux_tier2:
    permissions:
      contents: read # to fetch code (actions/checkout)

    name: Docker Linux Tier2
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      # max-parallel: 12
      matrix:
        target: [
          wasm32-unknown-emscripten,
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: TARGET=${{ matrix.target }} sh ./ci/install-rust.sh
      - name: Execute run-docker.sh
        run: LIBC_CI=1 sh ./ci/run-docker.sh ${{ matrix.target }}
